name: Python Linting and Formatting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_HOME=/etc/poetry python3 -
          make install

      - name: Lint
        run: make lint

      - name: Format
        run: make format
